import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    appName: 'NARAKA AIR SERVICES',
    home: 'Home',
    bookings: 'Bookings',
    services: 'Services',
    profile: 'Profile',
    support: 'Support',
    flights: 'Flights',
    umrah: 'Umrah Packages',
    visa: 'Visa Services',
    hotels: 'Hotels',
    login: 'Login',
    register: 'Sign Up',
    logout: 'Logout',
    welcome: 'Welcome',
    explore: 'Explore the world with us',
    bookFlight: 'Book Flight',
    bookUmrah: 'Book Umrah',
    contactUs: 'Contact Us',
    chatSupport: 'Chat Support',
    featuredDeals: 'Featured Deals',
    viewAll: 'View All',
    from: 'From',
    bookNow: 'Book Now',
    inquire: 'Inquire',
    searchFlights: 'Search Flights',
    origin: 'From',
    destination: 'To',
    departure: 'Departure',
    return: 'Return',
    passengers: 'Passengers',
    search: 'Search',
    oneWay: 'One Way',
    roundTrip: 'Round Trip',
    economy: 'Economy',
    business: 'Business',
    firstClass: 'First Class',
    selectPackage: 'Select Package',
    packageIncludes: 'Package Includes',
    price: 'Price',
    duration: 'Duration',
    visaType: 'Visa Type',
    requirements: 'Requirements',
    processingTime: 'Processing Time',
    submitInquiry: 'Submit Inquiry',
    fullName: 'Full Name',
    email: 'Email Address',
    phone: 'Phone Number',
    message: 'Message',
    send: 'Send',
    bookingHistory: 'Booking History',
    noBookings: 'No bookings yet',
    notifications: 'Notifications',
    deals: 'Deals',
    confirmations: 'Confirmations',
    admin: 'Admin Panel',
    manageBookings: 'Manage Bookings',
    managePackages: 'Manage Packages',
    totalBookings: 'Total Bookings',
    totalRevenue: 'Total Revenue',
    pending: 'Pending',
    confirmed: 'Confirmed',
    language: 'Language',
    english: 'English',
    hausa: 'Hausa',
    hello: 'Hello',
    guest: 'Guest',
    signInToContinue: 'Sign in to continue',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    bookingRef: 'Booking Reference',
    status: 'Status',
    date: 'Date',
    details: 'Details',
    close: 'Close',
    comingSoon: 'Coming Soon',
    payNow: 'Pay Now',
    securePayment: 'Secure Payment',
    cardNumber: 'Card Number',
    expiry: 'Expiry Date',
    cvv: 'CVV',
    pay: 'Pay',
    cancel: 'Cancel',
    success: 'Success',
    bookingConfirmed: 'Your booking has been confirmed!',
    inquirySent: 'Your inquiry has been sent. We will contact you soon.',
    error: 'Error',
    fillAllFields: 'Please fill all required fields',
    liveChat: 'Live Chat',
    whatsapp: 'WhatsApp',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    ourAddress: 'Our Address',
    quickLinks: 'Quick Links',
    popularDestinations: 'Popular Destinations',
    testimonials: 'What Our Clients Say',
    trust: 'Trusted Travel Partner',
    since: 'Serving since 2010',
    searchResults: 'Search Results',
    noResults: 'No results found',
    filter: 'Filter',
    sortBy: 'Sort By',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
  },
  ha: {
    appName: 'NARAKA AIR SERVICES',
    home: 'Babban Shafi',
    bookings: 'Lissafin Biki',
    services: 'Ayyuka',
    profile: 'Bayananka',
    support: 'Taimako',
    flights: 'Jiragen Sama',
    umrah: 'Bikin Umrah',
    visa: 'Ayyukan Visa',
    hotels: 'Hoteĩu',
    login: 'Shiga',
    register: 'Yi Rubutu',
    logout: 'Fita',
    welcome: 'Barka da zuwa',
    explore: 'Bincika duniya tare da mu',
    bookFlight: 'Yi Biki Jiragen Sama',
    bookUmrah: 'Yi Biki Umrah',
    contactUs: 'Tuntube Mu',
    chatSupport: 'Taimako ta Chat',
    featuredDeals: 'Kyautataken Saye',
    viewAll: 'Duba Duka',
    from: 'Daga',
    bookNow: 'Yi Biki Yanzu',
    inquire: 'Tambaya',
    searchFlights: 'Nemo Jiragen Sama',
    origin: 'Daga',
    destination: 'Zuwa',
    departure: 'Fita',
    return: 'Dawowa',
    passengers: 'Fasinjoji',
    search: 'Nemo',
    oneWay: 'Hanya Daya',
    roundTrip: 'Tafiya Biyu',
    economy: 'Tattalin Arziki',
    business: 'Kasuwanci',
    firstClass: 'Farko Class',
    selectPackage: 'Zaɓi Package',
    packageIncludes: 'Abubuwan da Package ke Haushe',
    price: 'Farashin',
    duration: 'Yawan Lokaci',
    visaType: 'Nauin Visa',
    requirements: 'Bukatukan',
    processingTime: 'Lokacin Aiwatarwa',
    submitInquiry: 'Aika Tambaya',
    fullName: 'Cikakken Suna',
    email: 'Adireshin Email',
    phone: 'Lambar Wayya',
    message: 'Sako',
    send: 'Aika',
    bookingHistory: 'Tarihin Lissafin Biki',
    noBookings: 'Babu lissafin biki tukuna',
    notifications: 'Sanarwa',
    deals: 'Kyautatake',
    confirmations: 'Tabbatattun',
    admin: 'Shafin Admin',
    manageBookings: 'Gudanar da Lissafin Biki',
    managePackages: 'Gudanar da Packages',
    totalBookings: 'Jimillar Lissafin Biki',
    totalRevenue: 'Jimillar Kasa',
    pending: 'Ana Jira',
    confirmed: 'An Tabbatar',
    language: 'Yare',
    english: 'Turanci',
    hausa: 'Hausa',
    hello: 'Sannu',
    guest: 'Bako',
    signInToContinue: 'Shiga domin ci gaba',
    password: 'Kalmar Sirri',
    confirmPassword: 'Tabbatar da Kalmar Sirri',
    forgotPassword: 'An Manta Kalmar Sirri?',
    createAccount: 'Birni Account',
    alreadyHaveAccount: 'Kana da account?',
    dontHaveAccount: 'Ba ka da account?',
    bookingRef: 'Lambar Lissafin Biki',
    status: 'Matsayi',
    date: 'Kwanan Wata',
    details: 'Cikakken Bayani',
    close: 'Rufe',
    comingSoon: 'Zai zo da Sauri',
    payNow: 'Biya Yanzu',
    securePayment: 'Biya Mai Tsaro',
    cardNumber: 'Lambar Kati',
    expiry: 'Lokacin Karewa',
    cvv: 'CVV',
    pay: 'Biya',
    cancel: 'Soke',
    success: 'Nasara',
    bookingConfirmed: 'An tabbatar da lissafin biki!',
    inquirySent: 'An aika tambayarka. Za mu tuntube ka da wuri.',
    error: 'Kuskure',
    fillAllFields: 'Da fatan za a cika duk filayen da ake bukata',
    liveChat: 'Chat Kai Tsaye',
    whatsapp: 'WhatsApp',
    callUs: 'Kira Mu',
    emailUs: 'Aika Email',
    ourAddress: 'Adireshin Mu',
    quickLinks: 'Hanyoyin Sauri',
    popularDestinations: 'Makamantan Zuga',
    testimonials: 'Abin da Abokanmu ke Cewa',
    trust: 'Aboki na Tafiya da Ake Aminta',
    since: 'Aiki tun 2010',
    searchResults: 'Sakamakon Nemo',
    noResults: 'Babu sakamako',
    filter: 'Tace',
    sortBy: 'Tsara ta',
    priceLowHigh: 'Farashi: Kasa zuwa Manya',
    priceHighLow: 'Farashi: Manya zuwa Kasa',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('narakalang') || 'en');

  useEffect(() => {
    localStorage.setItem('narakalang', lang);
  }, [lang]);

  const t = (key) => translations[lang][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);